defaults: &defaults
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      production:
        sessions:
          default:
            uri: <%= ENV['MONGOLAB_URI'] %>

development:
  <<: *defaults
production:
  <<: *defaults