defaults: &defaults
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        consistency: :strong
        safe: true
  options:
    raise_not_found_error: true

production:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults
